
[hashids]
    length = 12
    secret = "6ab6122836cfef95f8db"

[language]
    local = "zh-cn"

[mail]
    host = "smtp.163.com"
    pass = ""
    port = 465
    to = ""
    user = ""

[mysql]

    [mysql.base]
        connmaxlifetime = 60
        maxidleconn = 60
        maxopenconn = 10

    [mysql.read]
        addr = "175.178.183.117:3306"
        name = "fileupdata"
        pass = "7ihJXtb6KpaGcGJc"
        user = "fileupdata"

    [mysql.write]
        addr = "175.178.183.117:3306"
        name = "fileupdata"
        pass = "7ihJXtb6KpaGcGJc"
        user = "fileupdata"

    [redis]
        addr = "127.0.0.1:6379"
        db = "0"
        maxretries = 3
        minidleconns = 5
        pass = ""
        poolsize = 10